# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-UK

# Site timezone
timezone: Europe/London

# Site title
title: "Home Page"

# A description of your site for meta tag, search engine results.
description: "This is a personal website for Linquan Sun"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://linquans.github.io"

github:
  username: LinquanS

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
#   - text: Home
#     url: /
  - text: About
    url: /about/

# The shortname for your Disqus site to enable comments.
disqus: 

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
